#! /usr/bin/env python3
# -*- coding: utf-8 -*-
# ## ################################################################
# Date: 06/16/2023
# Name: "Guess the number"
# Author: Blanco Pulido Gabriel Alonzo
# License: MIT
# ## ################################################################
import sys
import random


def welcome_game_art():
    print("""
                             _   _                                  _               
                            | | | |                                | |              
  __ _ _   _  ___  ___ ___  | |_| |__   ___   _ __  _   _ _ __ ___ | |__   ___ _ __ 
 / _` | | | |/ _ \/ __/ __| | __| '_ \ / _ \ | '_ \| | | | '_ ` _ \| '_ \ / _ \ '__|
| (_| | |_| |  __/\__ \__ \ | |_| | | |  __/ | | | | |_| | | | | | | |_) |  __/ |   
 \__, |\__,_|\___||___/___/  \__|_| |_|\___| |_| |_|\__,_|_| |_| |_|_.__/ \___|_|   
  __/ |                                                                             
 |___/                                                                              
""")
# end welcome_game


def random_number():
    aux = list(range(1, 101))
    number_function = random.choice(aux)
    return number_function
# end random_number


def difficulty():
    difficult = "none"
    while difficult not in ["easy", "hard"]:
        difficult = input("\nChoose a difficulty. Type 'easy' or 'hard': ")
        if difficult not in ["easy", "hard"]:
            print("\nInvalid answer!, select a valid difficult.")
        elif difficult == "easy":
            return 10
        else:  # if difficult == hard
            return 5
# end difficulty


def main(argv):
    welcome_game_art()
    print("Welcome to the number guessing game!\n")
    number = random_number()
    print("I'm thinking of a number between 1 and 100\n")
    tries = difficulty()

    print(number)
    number_user = 0
    for i in range(tries):
        number_user = int(input(f"\nAttempt {i+1} of {tries}\nMake a guess: "))
        if number_user < number:
            print(f"{number_user} is too low.")
        elif number_user > number:
            print(f"{number_user} is too high.")
        else:
            print("\nYou guessed the number! Congratulations\n")
            break

    if number_user != number:
        print("\nYou've run out of guesses, you lose")
# end main


if __name__ == '__main__':
    main(sys.argv)
